### ISSUE TITLE
Getting access to ISOMsg response to set fields in the next req to link transactions

### ISSUE THREAD

**Issue by mchhil-incomm** [tilln/jmeter-iso8583#108]
I send an ISOMsg req, get a response and I need to use some fields in the response to send the next ISOMsg req.

Consider an auth req (0100) followed by a completion (0220) where the completion needs an auth id in field 38 , a copy of what was received in the auth response. It could be any field that I can get using the isomsg.get(...)

Would like the ISOMsg resp saved in a variable or accessible somehow  and use the standard resp.get(field) to set data in the next req. Maybe put it in the JMeter props with a key like an rrn or the name of request. I don't know enough about JMeter, or plugins so please excuse my ignorance.

The isomsg req is currently not needed to be accessible as the scoped variables take care of data and I can set fields from a previous request in the new one..
If there are other ways to do this via the plugin and jpos methods please let me know.

**Comment by tilln** [comment]
Hi @mchhil-incomm 

Accessing the response is currently possible in two different ways:
1. Via the Sample Result:
    The [SampleResult](https://jmeter.apache.org/api/org/apache/jmeter/samplers/SampleResult.html) stores an ISOMsg dump that can be accessed 
    - in a ["JSR223 PostProcessor"](https://jmeter.apache.org/usermanual/component_reference.html#JSR223_PostProcessor) via [`prev.getResponseDataAsString()`](https://jmeter.apache.org/api/org/apache/jmeter/samplers/SampleResult.html#getResponseDataAsString()), though this is not terribly useful other than for debugging, or
    - in a ["CSS Selector Extractor"](https://jmeter.apache.org/usermanual/component_reference.html#CSS_Selector_Extractor), which can be used to extract fields into a JMeter Variable that can be used in the following Completion request via `${AuthId}`:
      ![image](https://github.com/user-attachments/assets/4fd774d9-b117-4901-b990-3a32b5e369fa)

2. Via the Sampler itself:
  The ISO8583 Sampler stores a reference to the received response.
  This can be accessed in a "JSR223 PostProcessor" via [`sampler.getResponse()`](https://github.com/tilln/jmeter-iso8583/blob/1.3/src/main/java/nz/co/breakpoint/jmeter/iso8583/ISO8583Sampler.java#L234). When used with Groovy (recommended) no class cast is required.
  For example, save the value in the same JMeter Variable as above:
  `vars.put("AuthId", sampler.getResponse()?.getString(38))`.

HTH

**Comment by mchhil-incomm** [comment]
Excellent. Thank you for the assistance, greatly appreciate it. Will try it out.

**Comment by mchhil-incomm** [comment]
Tried both the css selector and the sampler. They worked as expected. Learned something new, thank you @tilln
