### ISSUE TITLE
enhance server mode

### ISSUE THREAD

**Issue by galihlasahido** [tilln/jmeter-iso8583#11]
maybe a server mode jpos for simulator seem to be a great idea, using jpos-ee groovy will be a good for the selector and participant mode to make, not just by  second and end the thread like now.

**Comment by tilln** [comment]
@galihlasahido What you're suggesting sounds interesting, however, to be sure I understand what you mean exactly, perhaps you could provide an example of how you imagine that mode would work?

**Comment by galihlasahido** [comment]
first the server mode is something that only last for 60 second, i face some need for a server mode simulator, what i'm proposing is, making a new page like a non-testing element, why a non testing element, since it is a tools that will not be tested but for helping a transaction :
<img width="725" alt="Screen Shot 2019-10-06 at 14 30 05" src="https://user-images.githubusercontent.com/1109574/66265764-decee800-e845-11e9-8e06-5898af9ea30f.png">

<img width="1075" alt="Screen Shot 2019-10-06 at 14 33 48" src="https://user-images.githubusercontent.com/1109574/66265787-5866d600-e846-11e9-9505-2a52ab2069c1.png">

the page will some like this, don't forget to add for the space tag xml properties

```
<property name="space" value="tspace:defaultedc"/>
<property name="queue" value="mytxnqueueedc"/>
<property name="isorequest" value="REQUESTEDC"/>
<property name="isosource" value="ISOEDC"/>
```

and make a simple requestlistener to add the message to the space 

```
public class ISORequest implements ISORequestListener, Configurable {
    private Configuration cfg;
    private String space;
    private String isorequest;
    private String isosource;
    private String queue;
    private Long timeout;
    private LocalSpace sp;

    @Override
    public boolean process(ISOSource isoSource, ISOMsg isoMsg) {
        Context ctx = new Context();
        ctx.put(this.isosource, isoSource);
        ctx.put(this.isorequest, isoMsg);
        sp.out (this.queue, ctx, this.timeout);
        return true;
    }

    @Override
    public void setConfiguration(Configuration configuration) {
        this.cfg = configuration;
        this.space = this.cfg.get("space");
        this.isorequest = this.cfg.get("isorequest");
        this.isosource = this.cfg.get("isosource");
        this.queue = this.cfg.get("queue");
        this.timeout = this.cfg.getLong("timeout");
        sp = (LocalSpace) SpaceFactory.getSpace(this.space);
    }
}
```

and using the latest version of [http://jpos.org/maven/org/jpos/ee/jposee-groovy/2.2.7-SNAPSHOT/](url) or there is a 

```
GroovyRequestListener
The module provides a org.jpos.groovy.GroovyRequestListener class, which allows the writing of
org.jpos.iso.ISORequestListener's in Groovy.
``` 
[http://jpos.org/doc/jPOS-EE.pdf](url)

where we can just add a groovy file for RequestListener an also using it we can make the selector and the participant to a groovy file, maybe something like 

<img width="1067" alt="Screen Shot 2019-10-06 at 14 50 15" src="https://user-images.githubusercontent.com/1109574/66265964-dcba5880-e848-11e9-9816-1388b707e100.png">

it's just some what i imagine,

**Comment by tilln** [comment]
> i face some need for a server mode simulator

This plugin currently provides the ability to generate ISO8583 _request_ messages for load testing purposes.

What this issue seems to be about though is the ability to generate ISO8583 _response_ messages, either for script debugging (similar to the HTTP Mirror Server) or for stubbing/mocking downstream systems, back-ends, hosts.

I agree this would be a nice feature, but it looks rather complex to integrate that "server simulator" configuration with JMeter.

Happy to consider pull requests, but I would suggest using the jPOS EE Server Simulator as-is.

**Comment by tilln** [comment]
[Release 1.2](https://github.com/tilln/jmeter-iso8583/releases/tag/1.2) adds an optional "Request Listener" BeanShell script to the [ISO8583 Connection Configuration](https://github.com/tilln/jmeter-iso8583#iso8583-connection-configuration) that can be used to programmatically sends responses to incoming requests.

Simply add an _ISO8583 Connection Configuration_ in "server mode" (i.e. empty Hostname field) that will listen on the specified port and pass every message to the BeanShell script.

See also [issue 37](https://github.com/tilln/jmeter-iso8583/issues/37#issuecomment-800036366).
