### ISSUE TITLE
Custom EMV tag names support

### ISSUE THREAD

**Issue by Nzsquall** [tilln/jmeter-iso8583#12]
Hi @tilln ,

Do you plan on adding custom EMV tags support?

At the moment, if I pass in EMV tag names that are not defined in _org.jpos.emv.EMVStandardTagType_ class, I will get the following packing error:
`2019-10-07 16:18:26,087 ERROR n.c.b.j.i.ISO8583Sampler: Packager error on request 'Auth with EMV'. Check config! org.jpos.iso.ISOException: error packing field 55 (org.jpos.iso.ISOException: org.jpos.emv.UnknownTagNumberException: 9f6e (org.jpos.emv.UnknownTagNumberException: 9f6e))
`

Btw MACing with clear MAC session key works perfectly, well done :).

Cheers
Eric

**Comment by tilln** [comment]
This is a limitation of the BERTLVPackager which I assume you are using.
It is possible to extend this for proprietary tags via a custom BERTLVFormatMapper.
Have a look at https://github.com/jpos/jPOS/blob/v2_1_3/jpos/src/main/java/org/jpos/tlv/packager/bertlv/DefaultICCBERTLVFormatMapper.java#L56-L63

As such custom tags require custom code it is not straight-forward to add support to the plugin, so feel free to make suggestions on how to implement this in a generic way or even submit a pull request.

**Comment by Nzsquall** [comment]
Yeah I actually have to implement my own BERTLVFormatMapper, BERTLVPackager and EMVTagType class to support custom tags.

I can see it is not that easy, will need to think about this one a bit more.
