### ISSUE TITLE
MTI clarification

### ISSUE THREAD

**Issue by ydalley** [tilln/jmeter-iso8583#17]
Hello Tilln,

Thanks for an excellent tool.

can you clarify how the MTI response is mapped to the request with the 3 sets of 10 digit numbers?

> MTI Mapping: 3 ten-digit numbers representing how the first 3 MTI digits are mapped between request and response. Example (default): "0123456789 0123456789 0022446789" maps response MTI 0110 to request MTI 0100

**Comment by tilln** [comment]
Hi @ydalley 

You might want to have a look at [this reply](https://github.com/tilln/jmeter-iso8583/issues/4#issuecomment-524733577) as well as the [jPOS documentation](https://github.com/jpos/jPOS/blob/v2_1_3/doc/src/asciidoc/ch08/qmux.adoc#mti-mapping-and-default-key).

**Comment by ydalley** [comment]
ok, thanks. got it
