### ISSUE TITLE
org.jpos.iso.ISOException: Key fields not found - not sending jmeter-

### ISSUE THREAD

**Issue by yassin-mardi** [tilln/jmeter-iso8583#18]
hi, i'm learning this plugin and i read your explication but when i tried to test one of your examples i encoutered some problems i don't know if i did wrong or right but i know you can help me . here they are
![config](https://user-images.githubusercontent.com/57249899/72823993-d8d60900-3c74-11ea-8371-4f1cb8fc3c60.png)
![probleme 1](https://user-images.githubusercontent.com/57249899/72823994-d8d60900-3c74-11ea-90d5-3a4379986a1a.png)
![probleme2](https://user-images.githubusercontent.com/57249899/72823999-d96e9f80-3c74-11ea-8b3a-08494e3c8e79.png)
![sampler](https://user-images.githubusercontent.com/57249899/72824000-d96e9f80-3c74-11ea-98c1-4b8259030ea3.png)

**Comment by tilln** [comment]
The jPOS Mux used by this plugin matches responses to requests based on some [key fields](https://github.com/jpos/jPOS/blob/v2_1_3/doc/src/asciidoc/ch08/qmux.adoc#mti-mapping-and-default-key) in the message (default: 0/MTI, 11, 41). 
As you're not sending 11 and 41 the Mux can't do that matching and refuses to send your message.
So, you'd either have to add those key fields or [override the configuration](https://github.com/tilln/jmeter-iso8583#config) to use different fields that are present in your message (see also [issue 4](https://github.com/tilln/jmeter-iso8583/issues/4#issuecomment-524219132)).

**Comment by yassin-mardi** [comment]
can u suggest to me what to do because this technologie is really new for me and i didn't understand what u said before

**Comment by yassin-mardi** [comment]
can u show me a config example based on this XML :
<isopackager>
 <isofieldpackager id="1"
            name="CARD ACCEPTOR LOCATION"
            length="40"
            class="org.jpos.iso.IFB_BINARY"
            packager="org.jpos.iso.packager.GenericSubFieldPackager"
            emitBitmap="false"
            firstField="1"
            maxValidField="3">
        <isofield id="1" name="NAME"    length="25" pad="false" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="2" name="CITY"    length="13" pad="false" class="org.jpos.iso.IF_CHAR"/>
        <isofield id="3" name="COUNTRY" length="2"  pad="false" class="org.jpos.iso.IF_CHAR"/>
    </isofieldpackager>
</isopackager>

**Comment by yassin-mardi** [comment]
i can't find Mux settings maybe removed in jemeter 5.2

**Comment by tilln** [comment]
Those Mux settings are going to be in the next release, so you'd have to download the [1.1-SNAPSHOT](https://github.com/tilln/jmeter-iso8583/releases/tag/1.1-SNAPSHOT) for now.
What's probably easiest to get you started is to
- add appropriate `isofield`s for 0, 11 and 41 to you packager XML, and
- add fields 11 and 41 to your test message

**Comment by yassin-mardi** [comment]
hi again , i applied your advices and launched a test . the result give the iso message but some bits are red colored and the test failed here they r
![probleme1](https://user-images.githubusercontent.com/57249899/72978345-975d6f00-3dd6-11ea-904f-2410f8b486d5.png)
![probleme2](https://user-images.githubusercontent.com/57249899/72978354-9c222300-3dd6-11ea-9abf-c31b8e9f4b89.png)
![probleme3](https://user-images.githubusercontent.com/57249899/72978364-9e847d00-3dd6-11ea-8df3-6b386cbb9700.png)
