### ISSUE TITLE
Installation instructions in the README file

### ISSUE THREAD

**Issue by barspi** [tilln/jmeter-iso8583#21]
Under the installation section, for the  **Via Package from JMeter-Plugins.org** option, it says:

> Extract the zip package into JMeter's lib directory, then restart JMeter.

But the zip itself starts with the `lib` directory as root of the archive, so I think it should be extracted *one level up*, meaning, from JMeter's root directory

**Comment by tilln** [comment]
Updated.
Thanks, @barspi for pointing that out.
