### ISSUE TITLE
Response to 0800 message on server mode

### ISSUE THREAD

**Issue by suresh-pandi** [tilln/jmeter-iso8583#37]
JMeter in a server mode, we are receiving  0800 (sign on) message from authorisation server, not sure how to respond with 0810 message by reading field 11 and use the same value in responding with field 39. Please provide some guidance

**Comment by tilln** [comment]
Hi @suresh-pandi 

I have prepared a [snapshot release](https://github.com/tilln/jmeter-iso8583/releases/tag/1.2-SNAPSHOT-ISSUE37) that hopefully addresses your requirement.

The "ISO8583 Connnection Config" has a new item at the very bottom
![image](https://user-images.githubusercontent.com/19366960/111273292-833e9600-8698-11eb-84fe-7ebb614e1227.png)
where you can specify a BeanShell script file name that handles incoming requests such as 0800 sign-on etc.

This uses a jPOS [BeanShell Request Listener](http://jpos.org/doc/javadoc/org/jpos/bsh/BSHRequestListener.html) which works similar to the [BeanShell Filter](https://github.com/jpos/jPOS/blob/v2_1_4/doc/src/asciidoc/ch05/channel_filters.adoc#bshfilter) but does not seem to be described in the jPOS documentation.

Here is an example script that responds to any 0800 message with the same fields, except turning 0800 into 0810 and adding field 39.
```java
if ("0800".equals(message.getMTI())) {
    message.setResponseMTI();
    message.set(39, "00");
    source.send(message);
}
```

If you could please do some testing and provide feedback here.

**Comment by suresh-pandi** [comment]
@tilln Thanks for the snapshot release, i have tested this and it perfectly works fine.

**Comment by tilln** [comment]
Merged into master.
Please use [1.2-SNAPSHOT](https://github.com/tilln/jmeter-iso8583/releases/tag/1.2-SNAPSHOT) until v1.2 is released.
