### ISSUE TITLE
The latency is not recorded (The response time is)

### ISSUE THREAD

**Issue by leonartambunan** [tilln/jmeter-iso8583#38]
The latency is not recorded then the latency graph shows empty chart.
The ISO8583Sampler requires additional code to record the latency.

result.setLatency(timeAmount)

![Screenshot from 2021-03-17 19-41-31](https://user-images.githubusercontent.com/6858636/111471234-45ef0c80-875b-11eb-8a9c-9e7fa081a7d7.png)
![Screenshot from 2021-03-17 19-41-26](https://user-images.githubusercontent.com/6858636/111471506-8b133e80-875b-11eb-8aa7-d37e356dc2e9.png)

**Comment by tilln** [comment]
Measuring latency is not currently implemented.
I wouldn't know exactly how to define this in this context and whether the underlying jPOS library this plugin is built on supports the concept at all.

JMeter's [latency definition](https://jmeter.apache.org/usermanual/glossary.html#Latency) is the time difference from first byte out to first byte in. 

For ISO8583 messages that are generally quite small and may fit into a single network packet and are most likely sent over persistent TCP connections without the overhead of establishing a connection, the total response time (first byte out to last byte in) may not be much greater than the latency, so it may be debatable how useful its measurement would be.

@leonartambunan Please comment if you have suggestions how this could be defined and/or implemented or feel free to submit a pull request.

**Comment by leonartambunan** [comment]
Based on Jmeter samplers I have ever seen, usually the latency is juts the time spent from sampler started until prior to the return of the result.

**Comment by tilln** [comment]
Still not clear how latency would be measured.
There is currently no distinction between the arrival times of the first and last byte of the response message.
The former would define the latency, the latter the total response time.
