### ISSUE TITLE
0x03 character appended to field 123 causing a parsing error

### ISSUE THREAD

**Issue by Darthops** [tilln/jmeter-iso8583#42]
Using the Base24TCP channel, the final field I'm using, field 123, has a 0x03 character appended to it which is causing parsing errors when it is being processed on the server.

It's visible in the wireshark trace that I'm running and in the server logs

Do you know how I can remove this character?

Thanks

**Comment by tilln** [comment]
Hi @Darthops 

Both BASE24TCPChannel and BASE24Channel send a `0x03` as a message trailer:
https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/iso/channel/BASE24Channel.java#L86
https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/iso/channel/BASE24TCPChannel.java#L90

Why do you need to use that channel? Are you sure that is appropriate in your case?

There is no way for the plugin to change what the channel is doing (except by using a different channel).

**Comment by Darthops** [comment]
Thanks for your reply, we're trying to send a "1100" message to a system which processes the message data using JPOS.

We can see in the log that the receiving system gets the payload data and then tries to parse using jpos. At the moment it shows an extra character at the end of the message which we believe is due to the message trailer. 

I'm honestly not sure if it's the appropriate channel, it was chosen because in the logs it mentions base24 with regards to these messages.

Do you know how we can find out which channel is appropriate? 

Thanks for your help

**Comment by chhil** [comment]
Your spec should tell you what the communication protocol (headers and length of message formats) is and you will need to pick the right channel from jpos if one  exists or extend one and create your own.
