### ISSUE TITLE
Is there a way to add CSV list to any field

### ISSUE THREAD

**Issue by imhamzaazam** [tilln/jmeter-iso8583#46]
I want to configure DE 41 and DE 42 from a CSV file. Any way how to do that?

**Comment by tilln** [comment]
@imhamzaazam 

Yes, this should be very simple as you can use out-of-the-box JMeter functionality to do that: 

You would add a [CSV Data Set Config](https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config)

![image](https://user-images.githubusercontent.com/19366960/146993262-339c2610-c183-46c5-bd3a-63925488a666.png)

Assuming your CSV file has some headers...

|CARD_ACCEPTOR_TERM_ID|CARD_ACCEPTOR_ID_CODE|
|-|-|
|...|...|

...then these can be referenced like so:
![image](https://user-images.githubusercontent.com/19366960/146993147-71d73ae1-c5d2-4cfd-8b89-905f793accbd.png)
