### ISSUE TITLE
I want to save random STAN to a variable

### ISSUE THREAD

**Issue by imhamzaazam** [tilln/jmeter-iso8583#47]
Right now i have assigned random string to stan and I want to save it to a variable so I can log it in an excel file

11: ${__RandomString(6,012345678,)}

Any idea how i might do that?

**Comment by tilln** [comment]
That's pretty easy: [`__RandomString`](https://jmeter.apache.org/usermanual/functions.html#__RandomString), like most JMeter functions, takes as a last, optional parameter the name of a variable in which to store the function's output.

So you would simply do `11: ${__RandomString(6,012345678,STAN)}`
