### ISSUE TITLE
iso 8583: Getting invalid bitmap for my ISO message in JMeter for POS Purchase transaction

### ISSUE THREAD

**Issue by mdzeyaullah** [tilln/jmeter-iso8583#48]
I am new to ISO 8583 message. I am getting Invalid bitmap error in LB balancer logs where I am sending the request from JMETER.

    2.01.12 21:44:19.462 [     blr:16449792]D-BLR-10013: Read 12 bytes
     22.01.12 21:44:19.462 [     blr:16449792]CCTClient::check_after() - actived
     22.01.12 21:44:19.462 [     blr:16449792]CCTClient::check() ret:None
     22.01.12 21:44:19.462 [     blr:16449792]L-BLR-10017: Recv 12 bytes from 
     [265], ID[269616260] at 1642013059 462
     22.01.12 21:44:19.462 [     blr:16449792]D-ISOHDL-0001: Process field: h1
     22.01.12 21:44:19.462 [     blr:16449792]D-ISOHDL-0001: Process field: mti
     22.01.12 21:44:19.462 [     blr:16449792]E-ISOHDL-2005: Exceed end of msg, field[mti]
     22.01.12 21:44:19.462 [     blr:16449792]E-ISOHDL-0004: Error in parsing iso8583 msg, no 
 msgid generated
    22.01.12 21:44:19.462 [     blr:16449792]E-BLR-70003: Retrieve MsgInfo failed, src port: 
    
    22.01.12 21:44:19.462 [     blr:16449792]D-BLR-70024: Handler resp method return -1
    22.01.12 21:44:20.589 [     blr:16449792]D-BLR-10013: Read 15 bytes
     22.01.12 21:44:20.589 [     blr:16449792]L-BLR-10017: Recv 15 bytes from 
    [265], ID[2797415146] at 1642013060 589
    22.01.12 21:44:20.589 [     blr:16449792]D-ISOHDL-0001: Process field: h1
    22.01.12 21:44:20.589 [     blr:16449792]D-ISOHDL-0001: Process field: mti
    22.01.12 21:44:20.589 [     blr:16449792]D-ISOHDL-0001: Process field: 0
    22.01.12 21:44:20.589 [     blr:16449792]E-ISOHDL-1000: Invalid bitmap field, at msg offset[e]
    22.01.12 21:44:20.589 [     blr:16449792]E-ISOHDL-0004: Error in parsing iso8583 msg, no msgid 
      generated
      22.01.12 21:44:20.589 [     blr:16449792]E-BLR-70003: Retrieve MsgInfo failed, src port: 
    .
      22.01.12 21:44:20.589 [     blr:16449792]D-BLR-70024: Handler resp method return -1
     22.01.12 21:44:20.589 [     blr:16449792]CCTClient::check() ret:None'
I am seeing in JMeter debug log.

This is the packed request it is forming.

'313230304632333030374331323843323841303531363434303634373030313430323135373730303030303030303030303030303032303030313132323134323031303031343432323230313132303934323031373130333031373033333443303130303332303030343139393030333734323036353838383437303233373334383433353137383234393633363636363636363636363636363638353237343139363633333120202030303652414a425031303336383234374646463031303030303430303030303033373137305f2a020682820219808407a0000002281010950500000080019a032112149c01009f02060000000050009f03060000000000009f10120110a040002a00000000000000000000ffff9ff1a0206829f2608cfef18b5eaecb9949f2701809f3303e008089f34031f03029f3501229f3602003b9f3704055b6e3b50046d6164619f6e07068200003030009f120a6d6164612044656269744f07af00000022810109f1e08353030313030343830303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303131303232303330303431303530343030353030374e30303030303045303030303030303039303130303030303030303030313130303030303030303031323130333431383030303133313033343139303030313431333438313033343030313531353036303030393136303130313031303232423439313137424646464646464646'
JMeter request message:

    <isomsg direction="outgoing">
       
      <header>6000376D25</header>
      <field id="0" value="1200"/>
      <field id="1" value="F23007C128C28A05"/>
      <field id="2" value="4406470014021577"/>
      <field id="3" value="000000"/>
      <field id="4" value="000000000200"/>
      <field id="7" value="0112212717"/>
      <field id="11" value="1442"/>
      <field id="12" value="220112092717"/>
      <field id="22" value="71030170334C"/>
      <field id="23" value="0"/>
      <field id="24" value="200"/>
      <field id="25" value="1990"/>
      <field id="26" value="742"/>
      <field id="32" value="588847"/>
      <field id="35" value="37"/>
      <field id="37" value="147987678722"/>
      <field id="41" value="6366666666666666"/>
      <field id="42" value="852741966331"/>
      <field id="47" value="BANBP1"/>
      <field id="49" value="682"/>
      <field id="53" value="47FFF010000400000037" type="binary"/>
      <field id="55"  
      <field id="62" 
      <field id="64" value="2B49117BFFFFFFFF" type="binary"/>
      </isomsg>
Hex dump generated from request

    
Can any one guide us where is the issue with my request. Header we are passing is like this - 6000376D25 Is passing message length is mandatory? How to pass the message length in the beginning of the hex dump if it is mandatory?

**Comment by mdzeyaullah** [comment]
@tilln

**Comment by mdzeyaullah** [comment]
@tilln  Thanks for the response.
Do I need to share any other information to confirm the issue?

**Comment by tilln** [comment]
@mdzeyaullah 

You'll have to find out from your documentation, specification and/or server logs how to build your 1800 message.

As I doubt there is an issue with this plugin I don't think you need to share more information.

Bitmaps will be generated by JMeter, as documented. 

As for headers, some Channel classes generate dynamic headers, for others you can specify static headers in the Connection Config or Sampler.

Here you'll find a [sample echo message](https://github.com/tilln/jmeter-iso8583#iso8583-sampler).

**Comment by mdzeyaullah** [comment]
@tilln Thanks for your quick response.
 Is there any way to add the message length and TPDU before the iso message in JMeter?

**Comment by tilln** [comment]
@mdzeyaullah 
There are ways to do that, though why would you need to and not just let jPOS generate all that for you?
I'd suggest you try to find a Channel class that suits your needs. Otherwise you might have to implement your own, though I doubt that'll be necessary.

**Comment by mdzeyaullah** [comment]
The only challenge we have is to send the message length as 2 bytes before the message header.
I am using NACChannel in my request.

NACChannel | Talks with TCP based NACs Sends [LEN][TPDU][ISOMSG] (len=2 bytes network byte order)

**Comment by mdzeyaullah** [comment]
@tilln 
Is MUX setting mandatory ?
I was going through this
https://github.com/tilln/jmeter-iso8583/blob/master/src/main/resources/nz/co/breakpoint/jmeter/iso8583/ISO8583ConfigResources.properties

Mux.displayName=Mux Settings
mtiMapping.displayName=MTI Mapping
mtiMapping.shortDescription=3 ten-digit numbers representing how the first 3 MTI digits are mapped between request and response
muxKeyConfig.displayName=Mux Key Configuration
muxKeyConfig.shortDescription=Each row contains the key fields for a message type as per the MTI column, or for all messages if the MTI column is empty
muxKeyConfig.tableHeaders=MTI|Key Fields

**Comment by tilln** [comment]
@mdzeyaullah 

> The only challenge we have is to send the message length as 2 bytes before the message header. I am using NACChannel in my request.

Ok, though other Channel classes may do that as well. You'd have to experiment.
Hope that NACChannel is working for you now? Or are you still getting Bitmap errors?

> @tilln Is MUX setting mandatory ? I was going through this https://github.com/tilln/jmeter-iso8583/blob/master/src/main/resources/nz/co/breakpoint/jmeter/iso8583/ISO8583ConfigResources.properties

Mux settings are optional (as per documentation).
Often times, it just works with the sensible jPOS default settings, otherwise you can do some tweaks there, e.g. when you're getting timeouts due to the Mux not being able to match incoming response messages to previously sent out request messages.

**Comment by mdzeyaullah** [comment]
Thanks @tilln  for your response.

About NAC Channel: At least we are able to send the request to reach to the backend application server. Earlier it was rejected from the first interface like LB itself.
Actually, our data element 3 is getting the value of data element 4 at backend server and data element 4 is taking the value of next data element after 4 which is data element 7. 
So it seems the application expects some more initial bytes before the actual message.
Still I am getting bitmap errors. Actually I am passing bitmap as 723007C128C28A05 but its converting to F23007C128C28A05 in hex dump generation.

As I experimented till now I am seeing that only through NAC Channel our request is able to reach till the backend server.
Perhaps I am repeating my question - where exactly In JMeter we can set the whole ISO message length if it can be handled by JMeter? Otherwise, we will send the 2 byte message length before the ISO message if there is no place holder in JMeter.

**Comment by chhil** [comment]
Please list the packager you are using, your initial message dump shows

 

You need to use a packager that matches what the receiver expects and not use the generic one.

e.g. My custom packager xyz.xml being used
   

> Still I am getting bitmap errors. Actually I am passing bitmap as 723007C128C28A05 but its converting to F23007C128C28A05 in hex dump generation.

Leading 72 from 723007C128C28A05 in binary is 0111 0010 [Fields 2,3,4,7 are present]
Leading FF from F23007C128C28A05 in binary is 1111 0010  [Field 1,2,3,4,7 are present

The field data follows your bitmap and are assigned based on the which ones are '1'/set
So in the case of F23007C128C28A05
what was field 2 is put in field 1 so on and so forth.

The problem is your packager file which you probably have not configured and the generic bitmap packing is causing it to get packed incorrectly.

I do hope you are not manually setting the bitmap and letting jpos packager do it for you.

All you need to do is set the fields (do not try and update the bitmap, it taken care of by jpos).
Use the correct channel. NACCChannel is working for you, and the receiver is unpacking the data so there is no need for TPDU etc. 
Use the correct packager file with correct field level pckagers configured in it. Which seems to be a problem as the reciver is unpacking it based on how you packed it and the fields are off. So fix your packager.
