### ISSUE TITLE
ERROR while sending request to switch 

### ISSUE THREAD

**Issue by knav28** [tilln/jmeter-iso8583#50]
@tilln 

I am facing below issue while sending request to switch . Using this plugin first time .

pls find attached screen shot for details 
![66CE2417-0515-4E1E-99E4-5CF1798828A9](https://user-images.githubusercontent.com/99947168/154633064-ff263805-b5d2-4ae7-98cf-5328c8ab5fa9.jpeg)

**Comment by tilln** [comment]
Hi @knav28 

`jmeter.iso8583.channelReconnectDelay` has to be a value in milliseconds rather than true or false.

**Comment by mchhil** [comment]
There is a possibility that you have configured the property 
`jmeter.iso8583.channelReconnectDelay= true` instead of using a number.

This guess is based on your plugin is using  jpos 2.1.6 and ChannelAdaptor Line 274 is trying to parse the long value of reconnect-delay.
https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/q2/iso/ChannelAdaptor.java#L274-L275

**Comment by tilln** [comment]
@mchhil 

My guess exactly, except I spotted the jPOS version number 2.1.4 at the bottom of the screenshot :-)

**Comment by knav28** [comment]
Thanks for your response 

i am still facing some exception like in screen shot and also attached properties of jmeter for your Refference . So pls suggest on this issue and need any changes in properties too.

pls share me the location for latest jmeter plugin if jmeter-iso8583-1.2.jar that I am using it now .
![Uploading CE960B60-4365-4136-8FCA-555736D1A4B7.jpeg…]()

**Comment by knav28** [comment]
![Uploading C66173CF-0DEB-43B8-8D8D-9B0CECB84AFB.jpeg…]()

**Comment by knav28** [comment]
![Uploading 5691DBA0-CE04-49AE-B059-BDAA44A3DBDC.jpeg…]()

**Comment by knav28** [comment]
![Uploading D232A8C8-64C7-426D-956A-209566A481FA.jpeg…]()

**Comment by knav28** [comment]
![Uploading image.jpg…]()

**Comment by mchhil** [comment]
You could make it easier by posting the text of the log instead of images.

**Comment by knav28** [comment]
Any suggestion on my issue above ?

**Comment by chhil** [comment]
There is probably a connection and the jmeter plugin is waiting to receive data and at the tcp level a SO_TIMEOUT occurs. Readtimeout is a normal java tcp exception.
Its also possible your configuration is not correct and causing read timeouts.

You can use a normal netstat command to check if the connection is there.

**Comment by knav28** [comment]
Thanks !
It looks like connection is not there as port and ip using in jmeter is not displayed in netstat command list .

is there way to establish connection from jmeter and to listen server port and ip ?

**Comment by chhil** [comment]
It's clearly mentioned in the usage section on the main page. Leave the hostname blank and set the port number you want to listen on.

https://github.com/tilln/jmeter-iso8583#iso8583-connection-configuration

```
Hostname:
Client mode (JMeter connects to switch socket): Name or IP address of the switch to connect to.
Server mode (switch connects to JMeter socket): Leave blank. JMeter will wait for incoming connection from the switch before starting threads (timeout configurable via JMeter property jmeter.iso8583.incomingConnectionTimeout).
```
