### ISSUE TITLE
ISO8583 doesn't receive any response with B24Channel but with PADChannel it failed to unpack

### ISSUE THREAD

**Issue by chad1st** [tilln/jmeter-iso8583#62]
**Describe the bug**
Hello @tilln, i want to ask about the jmeter iso8583 issue using your plugin, currently i'm trying to perform a load testing on a jmeter as a client to the iso server but when im trying to send the iso request it doesn't give me any response using the B24 Channel , and i'm also trying to switch channel with PAD Channel, it received a response but it said failed to unpack, can you help me?

Below are the logs using B24Channel
[JmeterB24Channel.txt](https://github.com/tilln/jmeter-iso8583/files/10713030/JmeterB24Channel.txt)

Though when i captured with wireshark it supposed to receive a request with b24channel
![Wireshark](https://user-images.githubusercontent.com/45510221/218250238-e733a683-f60b-46e6-a0e1-b37005744ae5.jpg)

Below are the logs for PADChannel
[JmeterPadChannel.txt](https://github.com/tilln/jmeter-iso8583/files/10713029/JmeterPadChannel.txt)

**Comment by tilln** [comment]
Hi @chad1st 

First, you're going to have to figure out what Channel fits your wire protocol.

Unfortunately, I can't help with that as I'm not much of an expert (no idea what starts with `ISO` and then presumably the message length in 4 hex digits) but you may want to post that question for example here: https://groups.google.com/g/jpos-users

Then you can start looking at the Packager configuration.
