### ISSUE TITLE
Amex channel sending the ISO8583 header two times when running the ISO through server mode

### ISSUE THREAD

**Issue by Anthony-Felix** [tilln/jmeter-iso8583#65]
**Issue Description:** 
Amex channel sending the ISO8583 header two times when running the ISO through server mode. we are receiving 0800 message from server with header and JMeter responding with 0810. when sending the response, Amex channel sending the header two times 

**Expected behavior:**
Amex channel to send header one time. 

**Incoming 0800 message:**

![Incoming 0800 message](https://user-images.githubusercontent.com/127285469/224230424-5b7c2c37-839c-49d2-9a9c-dc9c0329c230.jpg)

**Outgoing 0810 message**
![Outgoing 0810 message](https://user-images.githubusercontent.com/127285469/224230451-ce0803bc-7c84-48fa-bbca-827bad356600.jpg)

**Comment by tilln** [comment]
Hi @Anthony-Felix 

Can you please provide some more information:
- ISO8583 Connection Configuration(s)
- Request Listener script (assuming one is used to respond to the 0800 message)

Perhaps you can upload a minimal version of your JMeter script, with sensitive details redacted.

**Comment by Anthony-Felix** [comment]
Hi @tilln ,

Please find below the details asked for.

ISO8583 Connection Configuration(s)
![ISO8583_ConnectionConf1](https://user-images.githubusercontent.com/127285469/224613055-8d8f12cd-a92d-4f76-a396-3d6e4bc0cf12.png)

![ISO8583_ConnectionConf2](https://user-images.githubusercontent.com/127285469/224613077-6ad17ae9-b892-44ae-a026-21d86b17a437.png)


Request Listener script (assuming one is used to respond to the 0800 message)
![bsh_File](https://user-images.githubusercontent.com/127285469/224613158-22fb9e24-ee35-4a32-808c-32ab18e396eb.png)


Thanks in advance.

**Comment by tilln** [comment]
Thanks, @Anthony-Felix.

I can't see any header configuration though.

How is your script setting the header that appears twice on the response?

**Comment by Anthony-Felix** [comment]
Hi @tilln ,

We are using Header length in packager which automatically pick the header from 0800 and sending in 0810 response. Refer below the packager header length. While sending in 0810 it's sending header two times. Is there any way to resolve this. Thanks in advance.

![Packager](https://user-images.githubusercontent.com/127285469/225231469-3b276b47-a647-4932-95af-b79570fab110.png)

**Comment by tilln** [comment]
Ok, thanks. 
I'll try to find some time to look into this in more detail.

**Comment by tilln** [comment]
@Anthony-Felix 
I think this is working as intended, however, it may not be well documented on either the jPOS nor this plugin's side.

What's happening is that the Packager [packs the header](https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/iso/ISOBasePackager.java#L214-L216) into the byte array to be sent, and the Channel [sends the header](https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/iso/BaseChannel.java#L599-L600) in front of the packed bytes.

However, there is a config setting that avoids this:
Apparently, when the header is defined at the message level (as in your case where the packager has a `headerLength` defined), the Channel should set `override-header` to true, so the Channel [ignores](https://github.com/jpos/jPOS/blob/v2_1_6/jpos/src/main/java/org/jpos/iso/BaseChannel.java#L499) the message's header (at least BaseChannel and any Channel that does not override the method, such as AmexChannel).

![image](https://user-images.githubusercontent.com/19366960/225406621-e9daa390-96ab-442b-81bd-da7a40b434ab.png)

**Comment by Anthony-Felix** [comment]
Hi @tilln ,

Thank you. I'll try the above override-header and let you know the outcome.

Also, I've removed the header length in packager and tried to provide the header in connection configuration. when I did this, the 0810 doesn't send the 39 field as "00" to server. I need to further check this. Will update you both results.

**Comment by Anthony-Felix** [comment]
We are verified both methods and shared the results below.

Method1:
Passing ASCII header in sampler and defined header length as "0" in packager file.

![image](https://user-images.githubusercontent.com/127285469/226850791-ede5e530-a76f-4904-935d-dc9f9fdf43b9.png)

![image](https://user-images.githubusercontent.com/127285469/226850939-ed9a9dc4-82ea-4e72-ba00-ea48490b4957.png)

The header is passing single time in log but 39 field receiving the Empty value.

![image](https://user-images.githubusercontent.com/127285469/226857457-c6476e8e-cdd9-4d00-b770-a422ad925aa0.png)


Method2:
Removed ASCII header in ISO sampler and added the override-header in Advanced configuration.

![image](https://user-images.githubusercontent.com/127285469/226851694-5955b947-d26c-4a7c-8179-4c72bb82711f.png)

Modified header length as "21" in packager file.

![image](https://user-images.githubusercontent.com/127285469/226852005-52de6e2e-bd08-4b6f-a3d9-6cbe0240e867.png)

The header is passing single time in 0810 message but 39 field receiving the Empty value.

We're using the below beanshell for 39 field passing.

![image](https://user-images.githubusercontent.com/127285469/226852550-1bfe4fa8-f8a3-49d4-b207-7721fd4935cb.png)

**Comment by tilln** [comment]
Thanks, @Anthony-Felix for your detailed reply.
So the issue with the duplicate header is resolved.

Regarding field 39 being empty, I suggest double checking your packager configuration.
I could imagine you may have to send it as EBCDIC `F0 F0` rather than `00 00`.

**Comment by Anthony-Felix** [comment]
Thank you @tilln

We verified and modified the Packager as per your suggestion.

Now, we are receiving the "00" in 39 field.
