### ISSUE TITLE
iso8583 non blocking iso8583 send and receive

### ISSUE THREAD

**Issue by kg1h** [tilln/jmeter-iso8583#68]
@tilln Tilln when using the jmeter iso8583 sampler  under 1 thread loop 3 we are able to send and receive iso8583 messages for the first iteration successfully but in the second iteration not receiving any response (Using NACChanel FYI)

will jmeter support non blocking send and receive in asynchronous mode  ? we are able to run multiple send and receive isomessages through python using AsyncIO is there something similar in jmeter ?

**Comment by tilln** [comment]
Hi @kg1h 

Not sure I fully understand your issue and whether what you are after will fix it.

The sending and receiving is entirely handled by jPOS components, therefore it would make no difference if this plugin were to implement some async mode.

This plugin (synchronously) calls jPOS API methods (of class [QMux](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/q2/iso/QMUX.java#L132)) that will place messages in some type of queue (jPOS Space) where they wait to be sent over the Channel. When a response is received that will be made available in a similar queue and then matched with a request (based on some key fields). The response is then returned to the plugin and the JMeter thread can continue.

Perhaps you can elaborate a bit more what your experience and there may be another, simpler solution?
