### ISSUE TITLE
Please add ready to use jmx scenario for iso8583

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#71]
Please add ready to use jmx scenario for iso8583

**Comment by tilln** [comment]
@mehrdad2000 

I don't know whether this makes much sense given the variety of configuration parameters, e.g. different Channels and Packagers, request types etc.

Also, what endpoint would this "ready-to-use" script be targeting?

The fact that you have raised this suggests that you either struggle to get started based on the existing documentation, or that you think this may be useful for every user.

Happy to help if it's the former, and happy to accept PRs for the latter.

**Comment by tilln** [comment]
There is now a demo script under [samples](https://github.com/tilln/jmeter-iso8583/tree/main/samples).
