### ISSUE TITLE
Send message to mq with “queue name, channel name, …” through jmeter-iso8583 plugin

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#73]
I try to send message from jmeter-iso8583 to mq, but it’s not work.

here is the my current JSR223 sampler that work correctly and send “mymessage“ to mq, now question is how can i send output of iso8583 plugin to mq server?
Is it possible to add “queue manager, channel, user, pass, queue name,…) in connection manager of jmeter-iso8583?

import com.ibm.jms.JMSTextMessage;
import com.ibm.mq.jms.*;
import com.ibm.msg.client.wmq.WMQConstants;

import javax.jms.JMSException;
import javax.jms.Session;

MQQueueConnectionFactory cf = new MQQueueConnectionFactory();
cf.setHostName("192.168.1.1");
cf.setPort(1443); // or other port
cf.setIntProperty(WMQConstants.WMQ_CONNECTION_MODE, WMQConstants.WMQ_CM_CLIENT);
cf.setQueueManager("qm");
cf.setChannel("my.SVRCONN");
cf.setStringProperty(WMQConstants.USERID, "user");
cf.setStringProperty(WMQConstants.PASSWORD, "pass");
connection = (MQQueueConnection) cf.createQueueConnection();
MQQueueSession session = (MQQueueSession) connection.createQueueSession(false, Session.AUTO_ACKNOWLEDGE);
MQQueue queue = (MQQueue) session.createQueue("queue:///my.queue");
MQQueueSender sender = (MQQueueSender) session.createSender(queue);
JMSTextMessage message = (JMSTextMessage) session.createTextMessage("mymessage");
connection.start();
sender.send(message);

**Comment by tilln** [comment]
Hi @mehrdad2000 

You have to write your own Channel Class that wraps the JMS objects.

It would have to implement [ISOChannel](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/iso/ISOChannel.java) to be able to connect, send, receive etc. via JMS queue.

It should implement [Configurable](https://github.com/jpos/jPOS/blob/v2_1_8/jpos/src/main/java/org/jpos/core/Configurable.java) so you can pass in required properties via the test plan, for example:

![image](https://github.com/tilln/jmeter-iso8583/assets/19366960/b302576d-c083-4681-b478-b13605e7814b)

Below is an example of how you would access those properties.

You would also have to convert the `ISOMsg` that the ISO8583 Sampler generates into an appropriate JMS message, see below for an example.

```java
public class JMSChannel implements ISOChannel, Configurable {
    MQQueueConnectionFactory cf;
    // etc., your other JMS objects

    public void setConfiguration(Configuration cfg) throws ConfigurationException {
        // From common "Channel Settings":
        cf.setHostName(cfg.get("host"));
        cf.setPort(cfg.getInt("port"));
        // From "Advanced Configuration":
        cf.setQueueManager(cfg.get("queueManager");
        cf.setChannel("channel");
        // etc., your other config properties
    }

    public void send(ISOMsg isoMsg) throws IOException, ISOException {
        // Assuming your messages are send as bytes rather than text:
        BytesMessage jmsMsg = session.createBytesMessage();
        jmsMsg.writeBytes(isoMsg.getBytes());
        sender.send(jmsMsg);
    }
   // etc., other methods
}
```

I hope this gives you some ideas and a starting point.

**Comment by mehrdad2000** [comment]
@tilln Thank you for answer, would you please consider this as feature request and add channel for “jms channel”?
it would be useful feature for anyone who need send jms message.

Thanks

**Comment by tilln** [comment]
@mehrdad2000 
I'm happy to consider pull requests that add useful features.

**Comment by mehrdad2000** [comment]
@tilln should i do anything?

**Comment by tilln** [comment]
@mehrdad2000 how about implementing that channel class?
Or do you expect me to write your code for you?

**Comment by mehrdad2000** [comment]
Ok, I'm newbie in this case. if you guide me step by step I'll write it and create merge request.

**Comment by tilln** [comment]
@mehrdad2000 
Theoretically, it is possible, and you could re-use some functionality of this plugin, however, you would end up writing quite a bit of code too.
The challenge is that the ISO8583 Sampler builds the ISOMsg and expects to send it over the Channel.
If you don't want to send but only generate the message, you would have to avoid the Sampler altogether and re-write all the message generation.
So I suppose you're better off just creating that Channel class.

**Comment by mehrdad2000** [comment]
@tilln ok i’ll try to write below java code use base-channel as you mentioned, after compile this code it generates class file. What should i do next? Should i put class file in lib/ext directory of jmeter? Or it should be add into the iso8583.jar file to jmeter detect it?


Here is the code:

``` 

import org.jpos.iso.ISOChannel;
import org.jpos.iso.ISOException;
import org.jpos.iso.ISOMsg;
import org.jpos.iso.BaseChannel;
import org.jpos.core.Configuration;
import org.jpos.core.Configurable;
import org.jpos.core.ConfigurationException;

import javax.jms.*;
import com.ibm.mq.jms.*;

public class JMSChannel extends BaseChannel implements ISOChannel, Configurable {
    private MQQueueConnectionFactory cf;
    private MQQueueConnection connection;
    private MQQueueSession session;
    private MQQueueSender sender;

    public void setConfiguration(Configuration cfg) throws ConfigurationException {
        // Set JMS properties from configuration
        cf = new MQQueueConnectionFactory();
   try {
        cf.setHostName(cfg.get("host"));
        cf.setPort(cfg.getInt("port"));
        cf.setQueueManager(cfg.get("queueManager"));
        cf.setChannel(cfg.get("channel"));
        // Set other necessary properties (e.g., user ID, password)
   } catch (JMSException e) {


       throw new ConfigurationException("Error configuring JMS: " + e.getMessage());
    }
        // Create JMS objects
        try {
            connection = (MQQueueConnection) cf.createQueueConnection();
            session = (MQQueueSession) connection.createQueueSession(false, Session.AUTO_ACKNOWLEDGE);
            MQQueue queue = (MQQueue) session.createQueue("queue:///my.queue");
            sender = (MQQueueSender) session.createSender(queue);
        } catch (JMSException e) {
            throw new ConfigurationException("Error creating JMS objects", e);
        }
    }

    public void send(ISOMsg isoMsg) throws ISOException {
        try {
            // Convert ISO8583 message to JMS message
            BytesMessage jmsMsg = session.createBytesMessage();
            jmsMsg.writeBytes(isoMsg.getBytes());

            // Send JMS message to the queue
            sender.send(jmsMsg);
        } catch (JMSException e) {
            throw new ISOException("Error sending JMS message", e);
        }
    }

    // Implement other methods required by ISOChannel interface
    // (e.g., receive, connect, disconnect, etc.)
}

```

**Comment by tilln** [comment]
@mehrdad2000 
You may want to look at the JMeter [documentation](https://jmeter.apache.org/usermanual/get-started.html#classpath).

**Comment by mehrdad2000** [comment]
@tilln already read that page, the question is which is better?
1-create single jar file that contain this JMSChannel.class
2-add JMSChannel.class to jpos jar file in this path "org.jpos.iso.channel.JMSChannel"

Thanks

**Comment by tilln** [comment]
@mehrdad2000 
> the question is which is better?

I cannot answer that without knowing your quality criteria. Both should work though.

> `org.jpos.core.ConfigurationException: JMSChannel`

Instead of `JMSChannel` you have to use the fully qualified class name in you JMeter script, e.g. `org.jpos.iso.channel.JMSChannel`.

**Comment by mehrdad2000** [comment]
@tilln try it too 
![image](https://github.com/tilln/jmeter-iso8583/assets/26499665/ab4c6394-8bd9-4cc7-9011-c678c630905e)

**Comment by tilln** [comment]
Your source file is missing the package declaration.

**Comment by mehrdad2000** [comment]
@tilln declare package name and return exception error:
package org.jpos.iso.channel.JMSChannel1;

![image](https://github.com/tilln/jmeter-iso8583/assets/26499665/cd09e799-3d99-4fcc-8750-7883e36208dd)

**Comment by tilln** [comment]
@mehrdad2000 
Your package name must not include the class name:
`package org.jpos.iso.channel;`

**Comment by mehrdad2000** [comment]
@tilln modify code and pass that exception, now get below error:

2024-04-01 19:06:54,402 WARN n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) channel-sender-jmeter-345ee7f5-send
2024-04-01 19:06:54,403 WARN n.c.b.j.i.Q2: (org.jpos.q2.iso.ChannelAdaptor) hostname can't be null

FYI: hostname name and port filled correctly in channel settings.

any idea?
Thanks

**Comment by mehrdad2000** [comment]
@tilln instead of this line that you mentioned create new message:  BytesMessage jmsMsg = session.createBytesMessage();
need to get iso8583 sampler output to replace with "MYMESSAGE".

Any Idea?
Thanks
