### ISSUE TITLE
jmeter-iso8583 reply to request that recieve

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#74]
Hi
Is it possible to reply request with jmeter-iso8583 to iso message that receive from other node?
e.g. i config it in listen mode "does not set host name in channel setting" and other node connect to jmeter.
after that receive 0100 message from that node and need to send 0110 to reply that message.

is it possible with jmeter-iso8583 ?

Thanks

**Comment by tilln** [comment]
The "ISO8583 Connection Configuration" can define a "Request Listener" Groovy script that responds to incoming messages i.e. unsolicited messages that JMeter receives via that connection.
There is even an example in the README.
