### ISSUE TITLE
Server simulator

### ISSUE THREAD

**Issue by jadedani** [tilln/jmeter-iso8583#75]
Hi,

I have worked iso8583 sampler in JMeter. 

I've successfully simulated ISO8583 requests in JMeter's client mode. However, when attempting to use the ISO8583 sampler in server mode, I'm encountering issues.

I have used two instances of JMeter—one in client mode and the other in server mode. When sending multiple requests to the server mode JMeter, it initially responds to the first incoming messages but then disconnects, resulting in failures for the remaining messages.

My requirement is JMeter server mode used to perform load test.  

Kindly provide suggestion or advice?

**Comment by tilln** [comment]
Hi @jadedani 

What you describe is entirely possible, however, unless you can provide more details I can't diagnose your issue and figure out whether it's a bug in the plugin or whether your script is incorrect.

I have attached a very simple script that demonstrates how this can work, based on two ISO8583 Connection Configuration elements, one in "Client Mode", the other in "Server Mode" with a "Request Listener" script that responds to incoming messages.
You may of course decide to put those in two separate JMeter scripts but that wouldn't make much difference.

[issue75.zip](https://github.com/tilln/jmeter-iso8583/files/13479912/issue75.zip)
