### ISSUE TITLE
use value of fields in one sampler as variable in another sampler for creating 420 (reverse message)

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#80]
Hi
I have two samplers like this:

1-send 0200
2-send 0420

request bits of 0 11 13 12 32 33 first one must be pass as bit 90 in second one like this.
0=0200  11=917189  13=0309  12=090947  32=00000603799  33=00060376945
FYI1: zero in bit32 and 33 are padding.
FYI2:bit 11,12,13 generate by function of random date and number in sampler 0200

expected output bit90 in sampler message 0420 must be like this:
020091718903090909470000060379900060376945

FYI3: AFAIK regular expression extractor only available for response but i need to extract from request.

Any idea?
Thanks

**Comment by tilln** [comment]
I would suggest using one JMeter variable for each message field:
- Assign values to your variables before both request samplers, e.g. `vars.put('DE11', '917189')` etc.
- Use the individual variables in the 0200 request, e.g. `${DE11}`
- Use the concatenated variables in the 0420 request's field 90, e.g. `0200${DE11}${D12}${DE13}` etc.

**Comment by mehrdad2000** [comment]
@tilln should I use jrs223 or beanshield to extract variables?
 or like post processor regular expression there is a way to extract variable?

**Comment by mehrdad2000** [comment]
@tilln from request.
I thought it has tricky way without scripting like post processor regular expression that do this with response.

**Comment by tilln** [comment]
@mehrdad2000 
No, you can't do it without scripting.

**Comment by mehrdad2000** [comment]
@tilln  finally write Pre-Processor JRS223 script that do this:

```
def requestBody = prev.getSamplerData()
def ids = [0, 11, 12, 13, 32, 33]

ids.each { id ->
    def regex = /<field id="${id}" value="([^"]+)"\/>/
    def matcher = (requestBody =~ regex)
    if (matcher.find()) {
        def bit = id == 32 ? '00000' + matcher.group(1) : id == 33 ? '000' + matcher.group(1) : matcher.group(1)
        vars.put("bit${id}", bit)
       log.info("Extracted value for bit${id}: " + bit)
    }
}

```
