### ISSUE TITLE
packager iso2003ascii.xml

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#81]
Hi
looking for packager iso2003ascii.xml

check this link but it only has iso2003binary.xml
https://github.com/jpos/jPOS/tree/v2_1_8/jpos/src/dist/cfg/packager

Any idea?
Thanks

**Comment by tilln** [comment]
That's nothing to do with this plugin I'm afraid.
I suggest asking at https://groups.google.com/g/jpos-users
