### ISSUE TITLE
Using single jmeter instance to generate request and response 

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#82]
Hi
Is it possible to create message and send, then generate response with single jmeter instance (play role of client and server)? E.x. First start server then listen to port 8000 then client start to send requests.

Any idea? 
Thanks

**Comment by tilln** [comment]
First of all we should clarify what you mean by client and server:
- server as in listening for incoming TCP connections on a port, or responding to incoming ISO request messages, 
- client as in connecting to a TCP socket on a remote server, or sending ISO requests messages to a server (regardless of TCP connection "direction").

This plugin support multiple "ISO8583 Connection Configuration" elements, though each ISO8583 Sampler can only be assigned to one of those Config elements.
You may be aware of the Request Listener feature where you can specify a Groovy script to respond for incoming messages (incoming to JMeter, from remote test system).

**Comment by mehrdad2000** [comment]
@tilln if add two "ISO8583 Connection Configuration" first as server second as client, and start stuck at first one? And run second one after timeout? Or run both them parallel?

Is server stop client request does not get response.

Thanks

**Comment by tilln** [comment]
The server waits for an incoming connection for a configurable amount of time.
If that's "stuck" there may be no connection attempt from your test system.
Once the connection is established, they will run in parallel.

**Comment by mehrdad2000** [comment]
In the time the server waits, what happened? Client start? Or wait till first ISO8583 Connection Configuration finished?

FYI: both are in single host, single jmeter

**Comment by tilln** [comment]
It depends on the order of your two config elements.
Both are started sequentially before the threads are started that run the test.

**Comment by mehrdad2000** [comment]
@tilln if order of config are like this it will work?
1-Start server, 2-start client 
FYI: in single thread

**Comment by mehrdad2000** [comment]
@tilln is there any sample to generate request 100 and response 110? in single jmeter?

**Comment by tilln** [comment]
@mehrdad2000 
Not sure I understand what you are trying to do.
You mean you want your script to generate a `0100` message (via an ISO8583 Sampler) and also generate the `0110` response to the same message (via a Request Listener script in an ISO8583 Connection Configuration)?
That does not make much sense to me. Please elaborate.

**Comment by mehrdad2000** [comment]
@tilln exactly something like this:
https://github.com/adelbs/ISO8583

**Comment by tilln** [comment]
@mehrdad2000 
I don't know exactly what that tool does. So please try to answer my question.

**Comment by mehrdad2000** [comment]
@tilln request and response generate on same machine. looking for sample that do this via an ISO8583 Sampler.

**Comment by tilln** [comment]
You mean you want your script to generate a 0100 message (via an ISO8583 Sampler) and also generate the 0110 response to the same message (via a Request Listener script in an ISO8583 Connection Configuration)?

**Comment by mehrdad2000** [comment]
1-request 0100 generate by an ISO8583 Sampler.
2-response 0110 if it is possible (generate by an ISO8583 Sampler) if not by script.

**Comment by tilln** [comment]
I fail to understand whether you want to respond to the 0100 message from your first step, like a loop-back setup.

**Comment by mehrdad2000** [comment]
@tilln yes

**Comment by tilln** [comment]
I see.
Perhaps have a look at the sample attached [here](https://github.com/tilln/jmeter-iso8583/issues/75#issuecomment-1828555618)?

**Comment by mehrdad2000** [comment]
got this error after run that jmx:
024-03-16 14:56:35,459 ERROR n.c.b.j.i.ISO8583Config: Failed to deploy qserver
javax.management.InstanceAlreadyExistsException: server9999-server has already been deployed in another file.


2024-03-16 14:56:35,473 ERROR n.c.b.j.i.ISO8583Config: ISOServer not found
org.jpos.util.NameRegistrar$NotFoundException: server.server9999-server


FYI: groovy script and packager set correctly.
