### ISSUE TITLE
put generated message of jmeter iso8583 in jrs223 sample as variable

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#83]
Hi
I have 1-"ISO8583 Connection Configuration" and 2-"ISO8583 Sampler" and 3-"JRS223 Sampler"
need to put generated message of jmeter iso8583 in jrs223 sample as variable.

Any idea?
Thanks

**Comment by tilln** [comment]
@mehrdad2000 
This does not sound like an issue with this plugin.
Would you please consider posting questions like this elsewhere, e.g. under ["Discussions"](https://github.com/tilln/jmeter-iso8583/discussions).
