### ISSUE TITLE
Use MAC Generation function in JRS223 (groovy script)

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#84]
Hi
need to use function mac generation in groovy script jrs223.

try this  ${__generateDESKey(64,MAC)} but need to set MAC algorithm, MAC Key for this function.

is it possible to do this?

Any idea?
Thanks

**Comment by tilln** [comment]
@mehrdad2000 
This plugin does not provide a JMeter function for MAC generation.
Would you please consider posting questions like this under ["Discussions"](https://github.com/tilln/jmeter-iso8583/discussions).
