### ISSUE TITLE
Debug response packing using Jmeter dummy sampler?

### ISSUE THREAD

**Issue by Nzsquall** [tilln/jmeter-iso8583#9]
Hi @tilln ,

Apologize in advance if this is an obvious question.

There is a test plan I want to debug before I use it to hit the real application. So I want to use a simple mock to dispatch response, and see if the sampler can unpack it properly (with the real server response hex stream dump) for the next sampler request. This is also to test my packager.

I think this [dummy sample](https://jmeter-plugins.org/?search=jpgc-dummy) is my option, but I can't seem to get it working.

I have a simple 0800 request with all the data element fixed.

This is the hex dump when it is sent over the wire:
`2019-09-26 21:20:47,104 DEBUG n.c.b.j.i.ISO8583Sampler: Packed request '08008220000000000000040000000000000000008614121111110301'`

This is what it looks like when I capture the request with Wireshack (includes two bytes indicating the whole message length):
`001d0800822000000000000004000000000000000000861412111111030103`

I have configured my dummy sampler as below:
![image](https://user-images.githubusercontent.com/339124/65676844-b0624780-e0a4-11e9-8d87-90354d22e165.png)

Request data is the hex stream printed in the log (I also tried the one with 2 bytes length in front), and a hex stream response from the real application I captured.

For some reason I still get timeout on that sampler request:
![image](https://user-images.githubusercontent.com/339124/65676976-e69fc700-e0a4-11e9-87a6-095d43d6d110.png)

![image](https://user-images.githubusercontent.com/339124/65676993-ed2e3e80-e0a4-11e9-8259-1c1dd5a9c031.png)

Just wondering in your sampler development/test plan development, have you had to use something similar for debugging purpose? Can you please share a light of how you did it?

Thanks heaps.
Eric

**Comment by tilln** [comment]
The dummy sampler won't work as this creates a sample result that can be used as a substitute for the actual sampler's result to debug the rest of the JMeter script.

If you want to test the actual ISO8583 Sampler and the packager configuration, I suggest using the [jPOS EE Server Simulator](https://github.com/jpos/jPOS-EE/tree/master/modules/server-simulator) to send real requests to and configure it to respond with what you expect.
It's documented here: http://jpos.org/doc/jPOS-EE.pdf page 51, "10.1. Server Simulator".

**Comment by Nzsquall** [comment]
Thanks, will try that.
