### ISSUE TITLE
Feature Listbox for fields in iso 8583 sampler

### ISSUE THREAD

**Issue by mehrdad2000** [tilln/jmeter-iso8583#91]
Hi 
Is there anyway to add features that able users add listbox instead simple text box for each field in iso 8583 sampler.
E.g. i have 10 functions that generate different range of pan, it would be great if i able add list of 10 range in field2 and just select them when need them, instead of using jrs223 or any variables and etc … .

Any idea?
Thanks

**Comment by tilln** [comment]
> instead of using jrs223 or any variables

Sounds like you have a work-around.

Sorry, won't be implemented.
